FROM node:20-bullseye AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install


COPY nx.json tsconfig.base.json ./
COPY apps/tts-angular ./apps/tts-angular


RUN npm run build:tts




FROM nginx:alpine
COPY --from=builder /app/dist/apps/tts-angular /usr/share/nginx/html
COPY apps/tts-angular/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
